### ISSUE TITLE
Semantic Search using Embeddings

### ISSUE THREAD

**Issue by AliOsm** [meilisearch/meilisearch-rails#324] opened 2024-02-11 09:50 UTC
**Description**
Meilisearch is currently supporting vector search, I think adding support to meilisearch-rails for vector search will add a lot of values to ActiveModel and how to use them for searching. Instead of talking with the API directly.

**Basic example**
I created a very basic gem named [Chromable](https://github.com/AliOsm/chromable) to simplify the integration between Rails and ChromaDB. I think the same idea could be applied in meilisearch-rails.

**Comment by ellnix** [comment] 2024-02-11 19:42
This looks like a duplicate of #316

**Comment by curquiza** [comment] 2024-02-12 12:48
Closing in favor of #316 then

**Closed by curquiza** 2024-02-12 12:48 UTC
